import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from dotenv import load_dotenv
import os

from helpers.logger import logger


try:
    load_dotenv("secrets.env")

    # Email configuration
    SMTP_SERVER = os.getenv("SMTP_SERVER")
    SMTP_PORT = int(os.getenv("SMTP_PORT"))
    SMTP_USERNAME = os.getenv("TEST_MAIL")
    SMTP_PASSWORD = os.getenv("TEST_MAIL_PWD")
    SENDER_EMAIL = os.getenv("TEST_MAIL")
    RECIPIENT_EMAIL = os.getenv("KINDLE_MAIL")
    TELEBOT_KEY = os.getenv("TELEBOT_KEY")
except Exception as e:
    raise Exception(f"Failed to read secrets from env file: {e}")


def send_email(file_obj, filename):
    subject = 'Something to read'
    body = 'Email was generated by sendToKindleBot'

    message = MIMEMultipart()
    message['Subject'] = subject
    message['From'] = SENDER_EMAIL
    message['To'] = RECIPIENT_EMAIL

    # Add the body text
    message.attach(MIMEText(body, 'plain'))

    # Prepare the attachment from in-memory object
    file_obj.seek(0)
    attachment = MIMEApplication(file_obj.read())
    attachment.add_header('Content-Disposition', 'attachment', filename=filename)
    message.attach(attachment)

    try:
        with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT) as server:
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(message)
        return True
    except Exception as e:
        logger.error(f"Error sending email: {str(e)}")
        return False



if __name__ == "__main__":
    print(SMTP_SERVER)
    print(SMTP_PORT)
    print(SMTP_USERNAME)
    print(SMTP_PASSWORD)
    print(SENDER_EMAIL)
    print(RECIPIENT_EMAIL)
    print(TELEBOT_KEY)
