import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import os

from helpers.logger import logger


try:
    # Email configuration
    SMTP_SERVER = os.environ["SMTP_SERVER"]
    SMTP_PORT = int(os.environ["SMTP_PORT"])
    SMTP_USERNAME = os.environ["TEST_MAIL"]
    SMTP_PASSWORD = os.environ["TEST_MAIL_PWD"]
    SENDER_EMAIL = os.environ["TEST_MAIL"]
    TELEBOT_KEY = os.environ["TELEBOT_KEY"]
except Exception as e:
    raise Exception(f"Failed to read secrets from env file: {e}")


def send_email(file_obj, filename, username):
    subject = 'Something to read'
    body = 'Email was generated by sendToKindleBot'

    try:
        recipient_mail = os.environ[username]
        logger.info(f"Sending email to: {recipient_mail}")
    except KeyError:
        logger.error(f"Unknown user: {username}")
        return False


    message = MIMEMultipart()
    message['Subject'] = subject
    message['From'] = SENDER_EMAIL
    message['To'] = recipient_mail

    # Add the body text
    message.attach(MIMEText(body, 'plain'))

    # Prepare the attachment from in-memory object
    file_obj.seek(0)
    attachment = MIMEApplication(file_obj.read())
    attachment.add_header('Content-Disposition', 'attachment', filename=filename)
    message.attach(attachment)

    try:
        with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT) as server:
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(message)
        return True
    except Exception as e:
        logger.error(f"Error sending email: {str(e)}")
        return False



if __name__ == "__main__":
    print(SMTP_SERVER)
    print(SMTP_PORT)
    print(SMTP_USERNAME)
    print(SMTP_PASSWORD)
    print(SENDER_EMAIL)
    print(os.environ["Josef_Shveick"])
    print(TELEBOT_KEY)
