services:
  calibre_converter:
    container_name: calibre_converter_container
    image: calibre_converter_image:1.0.0
    build:
      context: ..
      dockerfile: docker/Dockerfile
#    ports:
#      - "80:5000"
#    env_file: ../secrets.env
