services:
  kindle_bot_aws:
    container_name: kindle_bot_aws_container
    image: kindle_bot_aws_image:1.2.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9000:8080"
    env_file: ../secrets.env
